name: cart_detail
description: "A new Flutter project."
 
publish_to: 'none'  

 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

 
dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  auto_route: ^9.0.0 
  google_fonts: ^4.0.4  
  flutter_stripe: ^10.2.0 # latest stable
  http: ^1.2.2
  flutter_dotenv: ^5.1.0 # for environment variables (API keys)
  ecommerce_app:
    path: ../../
  common:
    path: ../../core/common
  product_cart:
    path: ../../features/product_cart 

dev_dependencies:
  flutter_test:
    sdk: flutter

   
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.4

 
flutter:

 
  uses-material-design: true

   