on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master, develop]

name: "Melos CI | Analyze, Test, Build & Release"

jobs:
  melos_ci:
    name: Melos CI
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Run Pub Get in All Packages
        run: melos run pub_get_all

      - name: Clean, Sync, and Generate (build_runner)
        run: melos run all

      - name: Run Analyzer
        run: flutter analyze

      - name: Run Unit Tests
        run: melos run unit_test

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'  

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Build iOS (No Codesign)
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk,
            build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
